# Generated by Django 2.0 on 2019-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.TextField(max_length=200)),
                ('passwd', models.TextField()),
                ('name', models.TextField(default='')),
                ('email', models.TextField()),
                ('CreateTime', models.TextField()),
                ('LoginTime', models.TextField()),
                ('status', models.IntegerField(default='0', max_length=8)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
